---
title: "SF"
output: html_document
---


Primeiro teste, 3.28373

```{r}
train <- read.csv("~/Projetos/kaggle/San-Francisco-Crime-Classification/train.csv")
test <- read.csv("~/Projetos/kaggle/San-Francisco-Crime-Classification/test.csv")

library(rpart)
library(rattle)
library(RColorBrewer)
library(rpart.plot)


train$Date2 <- as.numeric(unclass(as.POSIXct(train$Dates)))
test$Date2 <- as.numeric(unclass(as.POSIXct(test$Dates)))


tree <- rpart(Category ~ X + Y + Date2 ,
              data = train,
              method = "class",
              control = rpart.control(minsplit = 200,cp=0)
              )

predicted <- predict(object = tree,newdata = test)
final <- data.frame(Id = test$Id , predicted)
colnames(final)  <- c("Id",levels(train$Category))

write.csv(data,file = "my_sub.csv",row.names = FALSE,quote = F)
```


Segundo teste, 3.28373

```{r}
train <- read.csv("~/Projetos/kaggle/San-Francisco-Crime-Classification/train.csv")
test <- read.csv("~/Projetos/kaggle/San-Francisco-Crime-Classification/test.csv")

library(rpart)
library(rattle)
library(RColorBrewer)
library(rpart.plot)


train$Date2 <- as.numeric(unclass(as.POSIXct(train$Dates)))
test$Date2 <- as.numeric(unclass(as.POSIXct(test$Dates)))


tree <- rpart(Category ~ X + Y + Date2 ,
              data = train,
              method = "class",
              control = rpart.control(minsplit = 200,cp=0)
              )

predicted <- predict(object = tree,newdata = test)
final <- data.frame(Id = test$Id , predicted)
colnames(final)  <- c("Id",levels(train$Category))

predicted2 <- predicted

predicted2 <- as.data.frame(predicted2)

predicted2[, "max"] <- apply(predicted2[, 1:39], 1, max)

data <- data.frame(Id = test$Id , predicted2[, "max"] == predicted2[, 1:40])

data[] <- lapply(data, function(x) as.integer(x))

data$Id <- as.integer(data$Id)

data$max <- NULL
colnames(data)  <- c("Id",levels(train$Category))

write.csv(data,file = "treeCategory.XYDate2.csv",row.names = FALSE,quote = F)

```

Complete tree:

```{r}
tree2 <- rpart(Category ~ .,
              data = train,
              method = "class",
              control = rpart.control(minsplit = 200,cp=0)
              )

predicted <- predict(object = tree2,newdata = test)
final <- data.frame(Id = test$Id , predicted)
colnames(final)  <- c("Id",levels(train$Category))

predicted2 <- predicted

predicted2 <- as.data.frame(predicted2)

predicted2[, "max"] <- apply(predicted2[, 1:39], 1, max)

data <- data.frame(Id = test$Id , predicted2[, "max"] == predicted2[, 1:40])

data[] <- lapply(data, function(x) as.integer(x))

data$Id <- as.integer(data$Id)

data$max <- NULL
colnames(data)  <- c("Id",levels(train$Category))

write.csv(data,file = "treeCategory.XYDate2.csv",row.names = FALSE,quote = F)
```

Random florest.

```{r}
randomflorest <- read.csv("~/Projetos/Kaggle/randomflorest")


final <- data.frame(Id = test$Id , randomflorest[,2:40])


#final[, "max"] <- apply(randomflorest[, 2:40], 1, max)

#data <- data.frame(Id = test$Id , final[, "max"] == final[, 2:41])

final[] <- lapply(final, function(x) as.integer(x))
#data["max"] <- NULL
colnames(final)  <- c("Id",levels(train$Category))
write.csv(final,file = "randomflorest3.csv",row.names = FALSE,quote = F)
```


```{r}
library(caret)
library(e1071)
library("C50")
library(plyr)

train$Date2 <- as.numeric(unclass(as.POSIXct(train$Dates)))
test$Date2 <- as.numeric(unclass(as.POSIXct(test$Dates)))

train_labels = train[, 2] ## Classes das instâncias de treino
train = train[-2] ## Exclui variável alvo

#Transformação para numeric
treino$PERIODO <- as.numeric(treino$PERIODO)
treino$DISCIPLINA <- as.numeric(treino$DISCIPLINA)
treino$DEPARTAMENTO <- as.numeric(treino$DEPARTAMENTO)
treino$SITUACAO <- as.numeric(treino$SITUACAO)
treino$MEDIA <- as.numeric(treino$MEDIA)

best_tree_model = train(train[c(7,8,9)], train_labels, method="C5.0", preProcess=c("range"))

predicted <- predict(object = best_tree_model,newdata = test)
final <- data.frame(Id = test$Id , predicted)
colnames(final)  <- c("Id",levels(train$Category))

write.csv(data,file = "my_sub.csv",row.names = FALSE,quote = F)

```


```{r}
predicted <- predict(object = tree,newdata = test)
final <- data.frame(Id = test$Id , predicted)
colnames(predicition)  <- c("Id",levels(train$Category))

predicition$Id <- test$Id
write.csv(predicition,file = "treeCategorydatepd.csv",row.names = FALSE,quote = F)
```

H20 tree with 50 tree, maxdepth 20

```{r}
rf5020 <- read.csv("~/Projetos/Kaggle/San-Francisco-Crime-Classification/rf5020")

colnames(rf5020)  <- c("Id",levels(train$Category))
rf5020$Id <- test$Id

write.csv(rf5020,file = "tree5020.csv",row.names = FALSE,quote = F)
```


H20 tree with 50 tree, maxdepth 20, total 

```{r}
rf5020total <- read.csv("~/Projetos/Kaggle/San-Francisco-Crime-Classification/rf5020total")

colnames(rf5020total)  <- c("Id",levels(train$Category))
rf5020total$Id <- test$Id

write.csv(rf5020total,file = "tree5020.csv",row.names = FALSE,quote = F)
```


H20 tree with 50 tree, maxdepth 20, newaddress

```{r}
rf5020totalnewAddress <- read.csv("~/Projetos/Kaggle/San-Francisco-Crime-Classification/rf-50-20-new")

colnames(rf5020totalnewAddress)  <- c("Id",levels(train$Category))
rf5020totalnewAddress$Id <- test$Id

write.csv(rf5020totalnewAddress,file = "tree5020totalnewAddress.csv",row.names = FALSE,quote = F)
```

H20 tree with 50 tree, maxdepth 20, newaddress without addresss

```{r}
rf5020totalnewAdd <- read.csv("~/Projetos/Kaggle/San-Francisco-Crime-Classification/rf-50-20-newadd")

colnames(rf5020totalnewAdd)  <- c("Id",levels(train$Category))
rf5020totalnewAdd$Id <- test$Id

write.csv(rf5020totalnewAdd,file = "tree5020totalnewAdd.csv",row.names = FALSE,quote = F)
```


Formatting address

```{r}
library(stringr)
test$newAddress <- str_to_lower(stri_replace_all_fixed(test$Address, " ", ""))
train$newAddress <- str_to_lower(stri_replace_all_fixed(train$Address, " ", ""))

train$Resolution <- NULL
train$Descript <- NULL

write.csv(train,file = "/home/rodolfo/Projetos/Kaggle/San-Francisco-Crime-Classification/train_adress.csv",row.names = FALSE,quote = F)

write.csv(test,file = "/home/rodolfo/Projetos/Kaggle/San-Francisco-Crime-Classification/test_adress.csv",row.names = FALSE,quote = F)
```


```{r}
train_dates <- train[1]
#?strptime
train_dates$Dates <- as.character(train_dates$Dates)
train_dates$Dates <- as.POSIXct(train_dates$Dates, format="%Y-%m-%d %H:%M:%S")

train_dates$Dates <- as.POSIXlt(train_dates$Dates)    # convert to 'POSIX list type'
train_dates$monthDay <- train_dates$Dates$mday
train_dates$hour <- train_dates$Dates$hour
train_dates$min <- train_dates$Dates$min
train_dates$mon <- train_dates$Dates$mon
train_dates$year <- train_dates$Dates$year
train_dates$wday <- train_dates$Dates$wday
train_dates$yday <- train_dates$Dates$yday
train_dates$week <- train_dates$Dates$yday / 7
train_dates$week <- as.integer(train_dates$week)

train <- cbind(train,train_dates)
colnames(train)


train[8] <- NULL


write.csv(train,file = "train_dates.csv",row.names = FALSE,quote = F)


test_dates <- test[2]
#?strptime
test_dates$Dates <- as.character(test_dates$Dates)
test_dates$Dates <- as.POSIXct(test_dates$Dates, format="%Y-%m-%d %H:%M:%S")

test_dates$Dates <- as.POSIXlt(test_dates$Dates)    # convert to 'POSIX list type'
test_dates$monthDay <- test_dates$Dates$mday
test_dates$hour <- test_dates$Dates$hour
test_dates$min <- test_dates$Dates$min
test_dates$mon <- test_dates$Dates$mon
test_dates$year <- test_dates$Dates$year
test_dates$wday <- test_dates$Dates$wday
test_dates$yday <- test_dates$Dates$yday
test_dates$week <- test_dates$Dates$yday / 7
test_dates$week <- as.integer(test_dates$week)

test_dates$Dates <- NULL

test <- cbind(test,test_dates)

write.csv(test,file = "test_dates.csv",row.names = FALSE,quote = F)



train_adress <- read.csv("/home/rodolfo/Projetos/Kaggle/San-Francisco-Crime-Classification/train_adress.csv")

test_adress <- read.csv("/home/rodolfo/Projetos/Kaggle/San-Francisco-Crime-Classification/test_adress.csv")
```

rf5020datenum

```{r}

rf5020date <- read.csv("~/rf5020date")

colnames(rf5020date)  <- c("Id",levels(train$Category))
rf5020date$Id <- test$Id

write.csv(rf5020date,file = "rf5020date.csv",row.names = FALSE,quote = F)
```

rf5020datesenum


```{r}

rf5020datesenum <- read.csv("~/rf5020datesenum")

colnames(rf5020datesenum)  <- c("Id",levels(train$Category))
rf5020datesenum$Id <- test$Id

write.csv(rf5020datesenum,file = "rf5020datesenum.csv",row.names = FALSE,quote = F)
```

rf5020someenums


```{r}

rf5020someenum <- read.csv("~/rf5020someenum")

colnames(rf5020someenum)  <- c("Id",levels(train$Category))
rf5020someenum$Id <- test$Id

write.csv(rf5020someenum,file = "rf5020someenum.csv",row.names = FALSE,quote = F)
```

rf7520someenums


```{r}
train <- read.csv("/home/viana/Projetos/Kaggle/San-Francisco-Crime-Classification/train.csv")

rf7520dates <- read.csv("~/rf7520dates")

colnames(rf7520dates)  <- c("Id",levels(train$Category))
rf7520dates$Id <- test$Id

write.csv(rf7520dates,file = "rf7520dates.csv",row.names = FALSE,quote = F)
```

rf7520add

```{r}
train <- read.csv("/home/viana/Projetos/Kaggle/San-Francisco-Crime-Classification/train.csv")
test <- read.csv("/home/viana/Projetos/Kaggle/San-Francisco-Crime-Classification/test.csv")

rf7520add <- read.csv("~/rf7520add")

colnames(rf7520add)  <- c("Id",levels(train$Category))
rf7520add$Id <- test$Id

write.csv(rf7520add,file = "rf7520add.csv",row.names = FALSE,quote = F)
rm(list = ls())
```